Ferlab-Ste-Justine/clin-prescription-ui

- cypress.config.ts
- src/components/Prescription/components/ClinicalSignsSelect/ObservedSignsList.tsx
> feat: CLIN-1898 Adjust Cypress tests

- src/components/Prescription/StepsPanel/index.tsx
- src/components/Prescription/components/ClinicalSignsSelect/NotObservedSignsList.tsx
- src/components/Prescription/components/ClinicalSignsSelect/index.module.scss
- src/locales/en.json
- src/locales/fr.json
> feat: CLIN-910 revamp clinical signs

- src/components/Prescription/components/PatientDataSearch/index.tsx
- closes #CLIN-1464
La date de naissance affichée dans le formulaire est la journée d’avant (2012-02-02) de la date de naissance du patient (2012-02-03).
[[JIRA LINK]](https://ferlab-crsj.atlassian.net/browse/CLIN-1464)
...
> fix: CLIN-1464 fix ddn

- src/locales/en.json
- src/locales/fr.json
- closes #CLIN-2139 & CLIN-2027
[JIRA LINK]
...
> feat: CLIN-2139 fix typos

- src/components/Prescription/Analysis/AnalysisForm/ReusableSteps/constant.ts
- src/components/Prescription/components/PatientDataSearch/index.tsx
- src/locales/en.json
- src/locales/fr.json
- src/utils/helper.ts
- closes #CLIN-1352
[JIRA LINK]
...
> fix: CLIN-1352 add validaton for mrn and first last name

- src/components/Prescription/Analysis/AnalysisForm/ReusableSteps/ParaclinicalExams/Review/index.tsx
- src/components/Prescription/Analysis/AnalysisForm/ReusableSteps/ParentIdentification/Review/index.tsx
- src/components/Prescription/components/ClinicalSignsSelect/ObservedSignsList.tsx
- src/locales/en.json
- src/locales/fr.json
- closes CLIN-1396
[JIRA LINK]
...
> fix: CLIN-1396 ajust empty state

- src/components/Prescription/components/PatientDataSearch/index.tsx
- closes CLIN-1352
[JIRA LINK]
...
> fix: CLIN-1352 ajust min length for first name and last name

- src/components/Prescription/components/PatientDataSearch/index.tsx
- src/locales/en.json
- src/locales/fr.json
- closes CLIN-1352
[JIRA LINK]
...
> fix: CLIN-1352 fix min char message and trigger

- src/components/Prescription/Analysis/AnalysisForm/ReusableSteps/ParaclinicalExams/Review/index.tsx
- src/components/Prescription/Analysis/AnalysisForm/ReusableSteps/ParentIdentification/Review/index.tsx
- src/components/Prescription/components/EmptySection/index.module.scss
- src/components/Prescription/components/EmptySection/index.tsx
- closes #CLIN-1396
[JIRA LINK]
...
> fix: CLIN-1396 color

- src/components/Prescription/components/ClinicalSignsSelect/index.module.scss
- src/components/Prescription/components/PatientDataSearch/index.tsx
- src/locales/en.json
- src/locales/fr.json
- closes #CLIN-2364
[JIRA LINK]
- https://ferlab-crsj.atlassian.net/browse/CLIN-2274
- https://ferlab-crsj.atlassian.net/browse/CLIN-2364
...
> fix: CLIN-2364 couple fixes

- src/views/Prescriptions/PractitionerTable/components/table/PrescriptionTable/columns.tsx
> fix: CLIN-2356 download documents column width

- src/components/Layout/Header/index.module.scss
- src/components/Layout/Header/index.tsx
> feat: CLIN-2312 beta tag behing feature toggle

- src/views/Home/components/ActionButton/index.module.scss
- src/views/Home/components/ActionButton/index.tsx
- src/views/Home/index.tsx
- closes #CLIN-2343
[JIRA LINK]
...
> feat: CLIN-2343 disable state for add parent home button

- .github/workflows/check_pull_request.yml
- .github/workflows/commit_lint.yml
- env-prod
- env-staging
- package.json
- src/providers/ApolloProvider.tsx
[[JIRA LINK]](https://ferlab-crsj.atlassian.net/browse/CLIN-2424)
Preparation pour `staging/prod`
> feat: CLIN-2424 keycloak rpt actions

- .gitignore
- cypress/e2e/FormulairesPrescription/CreationPrescription.cy.ts
- cypress/support/commands.ts
- closes [CLIN-2444](https://ferlab-crsj.atlassian.net/browse/CLIN-2444)
Mettre à jour les tests Cypress avec les ajustements accumulées.
> feat: CLIN-2444 Adjust Cypress tests

- src/api/form/models.ts
- src/components/Prescription/components/ParaclinicalExamsSelect/index.tsx
- src/locales/en.json
- src/locales/fr.json
> fix: CLIN-2421 added tooltip and added i18n

- src/components/Prescription/components/ClinicalSignsSelect/NotObservedSignsList.tsx
> fix: CLIN-2416 fixed wrong list of non-observed clinical signs

- src/components/Prescription/Analysis/AnalysisForm/ReusableSteps/PatientIdentification/AdditionalInformation/index.tsx
- closes #CLIN-2405
[[JIRA LINK]](https://ferlab-crsj.atlassian.net/browse/CLIN-2405)
Rendre le champ RAMQ de la mère de la section Informations supplémentaires requis.
...
> fix: CLIN-2405 fix ramq mere

- src/components/Prescription/components/ParaclinicalExamsSelect/index.tsx
> fix: CLIN-2423 removed tooltip on hover in multiselect options

- cypress/e2e/FormulairesPrescription/CreationPrescription.cy.ts
- src/api/form/index.ts
- src/components/Prescription/Analysis/AnalysisForm/ReusableSteps/Submission/index.tsx
- src/locales/en.json
- src/locales/fr.json
- src/store/prescription/slice.ts
- src/store/prescription/types.ts
- src/utils/constants.ts
- src/utils/helper.ts
- src/views/Home/index.module.scss
- src/views/Home/index.tsx
[[JIRA LINK]](https://ferlab-crsj.atlassian.net/browse/CLIN-2472)
...
> feat: CLIN-2472 implemented submitted prescription modal with download

- env-prod
- env-qa
- env-staging
#FEAT : Enlever le choix de la langue 
- closes #CLIN-2476
[[JIRA LINK]](https://ferlab-crsj.atlassian.net/browse/CLIN-2473)
...
> feat: CLIN-2475 enlever option langue header

- src/components/Prescription/Analysis/AnalysisForm/ReusableSteps/ParentIdentification/index.tsx
- src/locales/en.json
- src/locales/fr.json
> fix: CLIN-2443 added missing i18n

- src/views/Prescriptions/Detail/ClinicalInformationCard/components/Paraclinique/index.tsx
- src/views/Prescriptions/Detail/ClinicalInformationCard/components/Paraclinique/tests/paraclinique.spec.js
[[JIRA LINK]](https://ferlab-crsj.atlassian.net/browse/CLIN-1643)
> fix: CLIN-1643 Para-Clinical Value

- src/components/Layout/Header/index.tsx
- src/locales/en.json
- src/locales/fr.json
- closes #CLIN-2358
[[JIRA LINK]](https://ferlab-crsj.atlassian.net/browse/CLIN-2358)
...
> feat: CLIN-2358 changer nom onglet header

- src/locales/fr.json
- closes CLIN-2480
[JIRA LINK](https://ferlab-crsj.atlassian.net/browse/CLIN-2480)
...
> fix: CLIN-2480 lowercase after parenthese for fr

- src/locales/en.json
- src/locales/fr.json
- src/store/prescription/tests/utils.spec.js
- src/store/prescription/utils.ts
- closes CLIN-2429
[JIRA LINK](https://ferlab-crsj.atlassian.net/browse/CLIN-2429)
...
> fix: CLIN-2429 save the correct clinical signs for the prescription entity

- src/utils/helper.ts
- closes CLIN-2555
[JIRA LINK](https://ferlab-crsj.atlassian.net/browse/CLIN-2555)
...
> fix: CLIN-2555 add new char to special character rule

- src/locales/fr.json
- closes #CLIN-2395
Ajouter espace avant le ?
[JIRA LINK](https://ferlab-crsj.atlassian.net/browse/CLIN-2395)
...
> fix: CLIN-2395 fix modal cancel

- src/graphql/prescriptions/queries.tsx
- src/views/Home/index.tsx
- src/views/Prescriptions/PractitionerTable/components/table/PrescriptionTable/index.tsx
- src/views/Prescriptions/PractitionerTable/index.tsx
[[JIRA LINK]](https://ferlab-crsj.atlassian.net/browse/CLIN-2343)
> feat: CLIN-2343 prescription item count

- src/components/Prescription/components/HistoryAndDiagnosisData/index.tsx
- src/components/Prescription/utils/form.ts
- src/locales/en.json
- src/locales/fr.json
- closes CLIN-2440
[JIRA LINK](https://ferlab-crsj.atlassian.net/browse/CLIN-2440)
...
> fix: CLIN-2440 disable add button if previous value is empty

- src/components/Prescription/components/ClinicalSignsSelect/ObservedSignsList.tsx
- closes CLIN-2136
[JIRA LINK](https://ferlab-crsj.atlassian.net/browse/CLIN-2136)
...
> fix: CLIN-2136 skip validation when removing clinical sign

- src/components/Prescription/components/ParaclinicalExamsSelect/index.tsx
- closes PRESC-197
[JIRA LINK](https://ferlab-crsj.atlassian.net/browse/PRESC-197)
...
> fix: PRESC-197 paraclinical exams abnormal specification field is optional

- package-lock.json
- package.json
- src/api/form/index.ts
- src/utils/helper.ts
- src/views/Home/index.tsx
- src/views/Prescriptions/Detail/index.tsx
- src/views/Prescriptions/PractitionerTable/components/table/PrescriptionTable/columns.tsx
- src/views/Prescriptions/components/DownloadDocument/index.tsx
- closes #PRESC-190
[JIRA LINK](https://ferlab-crsj.atlassian.net/browse/PRESC-190)
...
> feat: PRESC-190 ajout bouton téléchargement

- cypress.config.ts
- cypress/e2e/AccesUtilisateurs/ParRole.cy.ts
- cypress/e2e/Consultation/PagePrescription.cy.ts
- cypress/e2e/Navigation/Landing.cy.ts
- cypress/e2e/Navigation/Login.cy.ts
- cypress/e2e/Navigation/Logout.cy.ts
- cypress/e2e/Navigation/Pages.cy.ts
- cypress/support/commands.ts
- cypress/support/index.d.ts
- env-qa
- closes #PRESC-231
[PRESC-231](https://ferlab-crsj.atlassian.net/browse/PRESC-231)
[PRESC-231]: https://ferlab-crsj.atlassian.net/browse/PRESC-231?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: PRESC-231 Adjust Cypress tests

- src/graphql/prescriptions/actions.tsx
- src/views/Home/index.tsx
- src/views/Prescriptions/PractitionerTable/index.tsx
- closes #PRESc-206
[JIRA LINK]
...
> fix: PRESC-206 rafraichir tableau

- src/components/PhenotypeTree/TransferModal/index.tsx
- closes PRESC-227
[JIRA LINK](https://ferlab-crsj.atlassian.net/browse/PRESC-227)
...
> fix: PRESC-227 hide hpo search and counts

- src/components/Prescription/Analysis/AnalysisForm/ReusableSteps/ParaclinicalExams/Review/index.tsx
- closes PRESC-235
[JIRA LINK](https://ferlab-crsj.atlassian.net/browse/PRESC-235)
...
> fix: PRESC-235 exam values can be undefined

- src/api/form/models.ts
- src/components/Prescription/Analysis/AnalysisForm/ReusableSteps/ParaclinicalExams/Review/index.tsx
- src/components/Prescription/components/ParaclinicalExamsSelect/index.tsx
- src/views/Prescriptions/Detail/ClinicalInformationCard/components/Paraclinique/index.tsx
- src/views/Prescriptions/Detail/ClinicalInformationCard/index.tsx
- closes PRESC-228
[JIRA LINK](https://ferlab-crsj.atlassian.net/browse/PRESC-228)
...
> feat: PRESC-228 manage form config for paraclinical signs that are required and have unit

- src/api/form/models.ts
- src/components/Prescription/Analysis/AnalysisForm/ReusableSteps/Submission/index.tsx
- closes PRESC-201
[JIRA LINK](https://ferlab-crsj.atlassian.net/browse/PRESC-201)
...
> fix: PRESC-201 adjust supervisor atocomplete behaviour and show supervisor license

- cypress/e2e/Consultation/PagePrescription.cy.ts
- src/views/Prescriptions/Detail/ParentCard/index.tsx
- src/views/Prescriptions/Detail/PatientCard/PatientContent/index.tsx
- src/views/Prescriptions/Detail/PatientCard/index.tsx
- src/views/Prescriptions/Detail/index.tsx
- closes PRESC-153
[JIRA LINK](https://ferlab-crsj.atlassian.net/browse/PRESC-153)
...
> feat: PRESC-153 add org reference afeter patient id

- src/locales/en.json
- src/locales/fr.json
- src/utils/translation.ts
> fix: PRESC-211 added translation

- src/components/Prescription/Analysis/AnalysisForm/ReusableSteps/PatientIdentification/AdditionalInformation/index.tsx
- closes PRESC-238
[JIRA LINK](https://ferlab-crsj.atlassian.net/browse/PRESC-238)
...
> fix: PRESC-238 no prenatal diagnostic if patient is male

- src/auth/keycloak.ts
- src/auth/rpt.ts
- src/store/prescription/slice.ts
- closes PRESC-240
[JIRA LINK](https://ferlab-crsj.atlassian.net/browse/PRESC-240)
...
> fix: PRESC-240 check token expiration on switching steps

- src/views/Prescriptions/Detail/ClinicalInformationCard/components/Paraclinique/index.tsx
- closes PRESC-242
[JIRA LINK](https://ferlab-crsj.atlassian.net/browse/PRESC-242)
...
> fix: PRESC-242 no more undefined paraclinical exam in prescription detail page

- src/views/Prescriptions/Detail/ClinicalInformationCard/components/Paraclinique/index.tsx
- src/views/Prescriptions/Detail/ClinicalInformationCard/index.tsx
- closes PRESC-243
[JIRA LINK](https://ferlab-crsj.atlassian.net/browse/PRESC-243)
...
> fix: PRESC-243 CGH is a complex paraclinical exam

- cypress/e2e/Consultation/PagePrescription.cy.ts
- src/api/fhir/models.ts
- src/graphql/prescriptions/queries.tsx
- src/views/Prescriptions/Detail/AnalysisCard/index.tsx
- src/views/Prescriptions/Detail/ParentCard/index.tsx
- src/views/Prescriptions/Detail/PatientCard/index.tsx
- closes PRESC-245
[JIRA LINK](https://ferlab-crsj.atlassian.net/browse/PRESC-245)
...
> fix: PRESC-245 get ep from patient managing org ref

- .gitignore
- cypress/e2e/Colonnes/TableauPrescriptions.cy.ts
- cypress/e2e/Consultation/TableauPrescriptions.cy.ts
- cypress/e2e/Navigation/Login.cy.ts
- cypress/support/commands.ts
- cypress/support/index.d.ts
- closes #PRESC-253
[PRESC-253](https://ferlab-crsj.atlassian.net/browse/PRESC-253)
[PRESC-253]: https://ferlab-crsj.atlassian.net/browse/PRESC-253?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: PRESC-253 Adjust Cypress tests

- src/graphql/prescriptions/actions.tsx
- src/graphql/prescriptions/queries.tsx
- src/locales/en.json
- src/locales/fr.json
- src/views/Prescriptions/Detail/AbsentParentCard/index.tsx
- src/views/Prescriptions/Detail/ParentCard/index.tsx
- src/views/Prescriptions/Detail/PatientCard/index.tsx
- src/views/Prescriptions/Detail/index.tsx
- closes PRESC-151
[JIRA LINK](https://ferlab-crsj.atlassian.net/browse/PRESC-151)
...
> fix: PRESC-151 show absent parents

- src/components/Prescription/Analysis/AnalysisForm/ReusableSteps/ParentIdentification/index.tsx
- closes PRESC-249
[JIRA LINK](https://ferlab-crsj.atlassian.net/browse/PRESC-249)
...
> fix: PRESC-249 fix validation for parent clinical info

- src/views/Prescriptions/Detail/ParentCard/index.tsx
- closes PRESC-199
[JIRA LINK](https://ferlab-crsj.atlassian.net/browse/PRESC-199)
...
> fix: PRESC-199 use correct affected status for parents

- src/components/Prescription/components/PatientDataSearch/index.tsx
- closes PRESC-257
[JIRA LINK](https://ferlab-crsj.atlassian.net/browse/PRESC-257)
...
> fix: PRESC-257 set no ramq value if search has value but no ramq

- src/components/Prescription/Analysis/AnalysisForm/ReusableSteps/PatientIdentification/Review/index.tsx
- src/views/Prescriptions/Detail/PatientCard/PatientContent/index.tsx
- closes PRESC-256
[JIRA LINK](https://ferlab-crsj.atlassian.net/browse/PRESC-256)
...
> fix: PRESC-256 patient folder organisation only if both ref and mrn present

- cypress/e2e/AccesUtilisateurs/ParRole.cy.ts
- cypress/e2e/Colonnes/TableauPrescriptions.cy.ts
- cypress/e2e/Consultation/PagePrescription.cy.ts
- cypress/e2e/Consultation/TableauPrescriptions.cy.ts
- cypress/e2e/FormulairesPrescription/CreationPrescription.cy.ts
- cypress/e2e/Navigation/Landing.cy.ts
- cypress/e2e/Navigation/Login.cy.ts
- cypress/e2e/Navigation/Logout.cy.ts
- cypress/e2e/Navigation/Pages.cy.ts
- cypress/plugins/index.ts
- cypress/support/commands.ts
- cypress/support/e2e.js
- cypress/support/index.d.ts
- closes #PRESC-268
[PRESC-268](https://ferlab-crsj.atlassian.net/browse/PRESC-268)
[PRESC-268]: https://ferlab-crsj.atlassian.net/browse/PRESC-268?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: PRESC-268 Ajust path case for Cypress tests
